### ISSUE TITLE
 Inquiry on Software Used for Circuit Diagram and Request to Share Source Files

### ISSUE THREAD

**Issue by xpww** [BoooC/CNN-Accelerator-Based-on-Eyeriss-v2#2]
Thank you for sharing this fantastic ASIC design project! The circuit diagram you created is exceptionally well-done, and I’m very interested in learning more about how it was created. Could you let me know which software you used to design this diagram? Additionally, if possible, would you consider allowing me to share the source files of the images ? I believe this would be incredibly helpful for educational and project reference purposes.

Thank you very much for your time!

Best regards.

**Comment by BoooC** [comment]
Thank you for your kind words! Actually, I created the diagram using Word’s built-in shapes, but I must admit that it’s not the most efficient tool for this purpose. If you’re looking to draw circuit diagrams, I’d recommend using Visio or the web-based version of draw.io instead. Both offer a more streamlined experience for this kind of work.

Thank you again for your interest!
